export let VA=(()=>{var z=new (self.AudioContext||self.webkitAudioContext),D=z.createGain(),N=D.gain.value=.2,H,r=b=>{H?(D.disconnect(),H.disconnect()):D.disconnect();(H=b)?D.connect(b).connect(z.destination):D.connect(z.destination)},d=new (self.OfflineAudioContext||self.webkitOfflineAudioContext)(2,2,z.sampleRate),v=b=>{try{b.stop()}catch(l){}try{b.disconnect()}catch(l){}try{b.buffer=null}catch(l){}},x=b=>{var l=z.createBufferSource();l.buffer=b;l.addEventListener("ended",()=>{v(l)},{once:!0});b=z.createStereoPanner?.();
var m=z.createGain();(b?l.connect(b):l).connect(m).connect(D);l.G=m;l.P=b;return l},u=[],n=(b,l=0,m=0)=>{if("suspended"==z.state||"interrupted"==z.state)try{z.resume()}catch(h){}if(b instanceof AudioBuffer){var A=x(b);if(!m){for(m=u.length-1;0<=m;m--){var [B,t]=u[m];B===b&&(t.G.gain.value/=2);t.buffer||u.splice(m,1)}u.push([b,A])}l||A.start();return A}},p={},G=0,J=()=>{var b=p.S;b&&v(b);b=p.X;p={};if(b){var [,l,m,A,B,t]=b,h=n(l,1,1);if(h){h.loop=!m;h.G.gain.value=A;h.playbackRate.value=B;var q=h.P?.pan;
q&&(q.value=t);p.Z=b;p.S=h;h.start()}else J()}},C=(b,l=0,m=1,A=1,B=1,t=0,h=!1)=>{h||=b;var q=p.S,E=p.Z;if(!q?.buffer||p.R||h!==E[0]||l!=E[2]||B!=E[3]||A!=E[4]||t!=E[5])if(G++,null==b||b instanceof AudioBuffer){if(p.X=b?[h,b,l,B,A,t]:null,!p.R){if(!q?.buffer||!q.G||!m)return J();p.R=!0;var y=99*m,k=q.G.gain.value/9,a=()=>0>=(q.G.gain.value-=k)||!q.buffer?J():setTimeout(a,y);setTimeout(a,y)}}else{C(null,!1,m);var f=G;e.L(b).then(g=>g&&f==G&&C(g,l,m,A,B,t,h))}};r(0);var c=z.createBuffer(1,2,z.sampleRate);
["touchstart","touchend"].forEach(b=>document.addEventListener(b,()=>n(c,0,1)));var e={L:async b=>{var l=await fetch(b);if(!l.ok)throw Error(b);b=await l.arrayBuffer();return await d.decodeAudioData(b)},P:n,BGM:C,D:v,I:r,get V(){return N},set V(b){N=b;D&&(D.gain.value=b)},get A(){return z},VER:"va99-5.3.20231110"};return e})();const aa=(()=>{const z=(d,v)=>{const x=n=>Array.isArray(n)?n.map(x):n?.constructor!==Object?n:1535027==n.type?d[n.Y]:Object.keys(n).reduce((p,G)=>(p[G]=x(n[G]),p),{}),u=Object.getPrototypeOf(Int8Array);return n=>{try{const p=x(n.data),G=v(...p),J=[],C=c=>c instanceof u?J.push(c.buffer):Array.isArray(c)?c.forEach(C):c?.constructor===Object?Object.values(c).forEach(C):c;C(G);postMessage(G,J)}catch(p){postMessage(p)}}},D=(d,v)=>{const [,,x]=d.B.shift();d.o=[,];d.H={};d.l&&d.l.terminate();d.l=0;x(v);
--d.M&&H(d)},N=d=>{var v="["+d.o.map(x=>x.toString()).join(",")+"]";v=URL.createObjectURL(new Blob(["onmessage=("+z.toString()+")("+v+","+d.$.toString()+")"],{type:"text/javascript"}));v=new Worker(v);v.onerror=x=>D(d,x);v.onmessage=x=>{x=x.data;const [,u,n]=d.B.shift();(x instanceof Error?n:u)(x);--d.M&&H(d)};return v},H=d=>{const v=u=>{const n=u.toString();var p=d.H[n];p||(p=d.o.length,d.o.push(u),p={type:1535027,Y:p},d.H[n]=p,d.l&&d.l.terminate(),d.l=0);return p},x=u=>Array.isArray(u)?u.map(x):
u?.constructor===Object?Object.keys(u).reduce((n,p)=>(n[p]=x(u[p]),n),{}):u?.constructor===Function?v(u):u;try{const [u]=d.B[0],n=x(u);(d.l||(d.l=N(d))).postMessage(n)}catch(u){D(d,u)}},r={};return(d,v)=>new Promise((x,u)=>{const n=r[d]||(r[d]={$:d,l:void 0,B:[],o:[,],H:{},M:0});n.B.push([v,x,u]);n.M++||H(n)})})();(()=>{const z=(r,d)=>{function v(c,e){let [b=0,l=1,m=[-1,1],A=2,B=[.01,.01,.2,.2],t=[1,.5,.5],h=[],q=[],E=[],y=0,k=0]=c;const [a=0,f=1]=e;Array.isArray(m)&&(c=m[0],m=c?.constructor===Function?c(...m.slice(1)):J(m));if(Array.isArray(y)){let [F,...I]=y;y=F(...I)}else if(Number.isFinite(y)){const F=y;y=I=>Math.sin(F*I*2*Math.PI)}if(Array.isArray(k)){let [F,...I]=k;k=F(...I)}else if(Number.isFinite(k)){const F=k;k=I=>Math.sin(F*I*2*Math.PI)}c=0;e=[];for(var g=0;g<B.length;g++){var w=B[g];w??=g?0:.001;
g==A&&(w*=f);w=Math.round(w*r);e[g]=c+w;c+=w}g=new Float32Array(c);let K=w=0,L=0,R=0,P=e[L],S=0,T=t[0]||0,U=0,V=h[0]||0,W=0,X=q[0]||0,Y=0,Z=E[0]||0;var O=220*2**((b+a)/12)/r;for(let F=0;F<c;F++){for(var Q=F/r;P<=F;)L++,R=P,P=e[L],S=T,T=t[L]||0,U=V,V=h[L]||0,W=X,X=q[L]||0,Y=Z,Z=E[L]||0;var M=P-R;M=M?(F-R)/M:0;O=m(K,w,O);const I=S+M*(T-S),ba=U+M*(V-U),ca=1+(W+M*(X-W))*(y?y(Q):0);Q=(Y+M*(Z-Y))*(k?k(Q):0);g[F]=l*O*I*ca;O=220*2**((b+a+ba+Q)/12)/r;K+=O;w+=K|0;K%=1}return[g]}function x(c){const e=Math.max(...c.map(t=>
t[0].length)),b=new Float32Array(e),l=new Float32Array(e);c.forEach(([t,h])=>{for(let q=0;q<e;q++)b[q]+=t[q]||0,l[q]+=h[q]||0});c=[b,l];let m=0;c.forEach(t=>{for(let h=0;h<e;h++)m=Math.max(m,Math.abs(t[h]))});const A=t=>{let h=Math.abs(t);if(1>h)return t;t=Math.sign(t);h=(h-1)/3+1;return 2>h?t*h:t*((h-2)/3+2)},B=A(m);if(.96<B){const t=.96/B;c.forEach(h=>{for(let q=0;q<e;q++)h[q]=A(h[q])*t})}return c}function u(c,e){function b(k){if(k.g){const a=Math.min(k.j,Math.round(.01*r));for(let f=0;f<a;f++){const g=
f/a;k.u[y-f]*=g;k.v[y-f]*=g}}}const l=c.i,m=c.c;c=c.s;const [A=0,B=1]=e,t=k=>{let a=[];for(let f=0;f<k.length;f++){let g=k[f];Array.isArray(g)?a=a.concat(t(g)):Number.isFinite(g)||!1===g||null==g?(a.push({T:99,U:g,W:k[f+1]}),f++):!0===g?(a.push({T:k[f+1],U:k[f+2],W:k[f+3]}),f+=3):g.constructor==Object&&a.push(g)}return a},h=m.map(k=>t(k));let q=h.map(()=>[[],[]]),E=120,y=0;for(e=h.map((k,a)=>({m:0,N:1,O:0,J:1,amplitude:.5,pan:0,C:h[a],F:0,u:q[a][0],v:q[a][1],g:void 0,j:void 0,K:!1,h:0}));!e.every(k=>
k.K);){let k=E;e.forEach(a=>{if(!a.K){for(;0>=a.h&&a.F<a.C.length;){var f=a.C[a.F++],g=f.T,w=f.U;f=f.W;if(99===g){if(null!=w)if(!1===w)b(a),a.g=null,a.j=null;else{Number.isFinite(w)||(w=0);b(a);g=l[a.m];const K=[A+a.O+w,B*a.J];w=[a.m,...K].join();a.g=p[w];a.g||(g=n(g,K),a.g=p[w]=g);a.j=0}f=f??1;Number.isFinite(f)||(f=1);a.h+=240/E*f/a.N}else 98!==g&&(1===w?a.m=C(a.m,f,g):6===w?a.N=C(a.N,f,g):5===w?a.O=C(a.O,f,g):7===w?k=C(k,f,g):2===w?a.J=C(a.J,f,g):3===w?a.amplitude=C(a.amplitude,f,g):4===w&&(a.pan=
C(a.pan,f,g)))}a.u[y]=0;a.v[y]=0;a.g&&(a.g[0].length<=a.j?(a.g=null,a.j=null):(f=a.g[0],g=a.g[1]||f,w=a.amplitude*Math.min(1,1+a.pan),a.u[y]=f[a.j]*a.amplitude*Math.min(1,1-a.pan),a.v[y]=g[a.j]*w,a.j++));0>=a.h&&a.C.length<=a.F&&(b(a),a.K=!0);0<a.h&&(a.h-=1/r)}});E!==k&&(e.forEach(a=>a.h*=E/k),E=k);y++}e=x(q);c&&(c*=r,e[0]=e[0].slice(c),e[1]=e[1].slice(c));return e}function n(c,e){return c?.constructor===Object?u(c,e):Array.isArray(c)?c.length&&c.every(b=>b instanceof Float32Array)?c:v(c,e):void 0}
const p={},G=(c,e,b,l,m=1)=>(c+e)/2-.5*(e-c)*Math.cos(Math.min(1,b*Math.max(1,.5/m/l))*Math.PI),J=c=>(e,b,l)=>{b=c.length;e*=b;const m=e|0;return G(c[m]||0,c[(m+1)%b]||0,e%1,l,b)},C=(c,e,b)=>Number.isFinite(e)?1==b?c+e:2==b?c-e:3==b?c*e:4==b?e?c/e:c:e:c;return n(d,[])},D=r=>{if(!r.length)return null;const d=VA.A.createBuffer(r.length,r[0].length,VA.A.sampleRate);r.forEach((v,x)=>d.getChannelData(x).set(v));return d},N=async(r,d)=>d?D(z(VA.A.sampleRate,r)):D(await aa(z,[VA.A.sampleRate,r])),H=VA.L;
VA.L=async(r,d=!1)=>{var v;r instanceof AudioBuffer?v=r:v=r?.constructor===String?H(r):r?.constructor===Object||Array.isArray(r)?N(r,d):H(r);return v};VA.VER+="+asg-0.0.20231112-SNAPSHOT"})();
//# sourceMappingURL=asg-va99.min.mjs.map
